GET http://localhost:3005/pedidos

###
GET http://localhost:3005/pedidos/1

###
DELETE http://localhost:3005/pedidos/1

###
POST http://localhost:3005/pedidos
Content-Type: application/json

{
    "data": "2024-10-03T01:37:33.434Z",
    "formaPagamento": "BOLETO",
    "valorTotal": 2399.99,
    "entrega": {
        "nome": "Tarcio Rodrigo",
        "cidade": "Cubatão",
        "estado": "São Paulo",
        "cpf": "28408664808",
        "email": "tr.rodrigo@gmail.com",
        "logradouro": "Rua Ofélia Marques de Meireles, 892",
        "complemento": "Casa"
    },
    "status": "RECEBIDO",
    "itens": [
        {
            "produto": {
                "id": 21,
                "nome": "Monitor Gamer LG UltraGear 34\"",
                "descricao": "O LG UltraGear 34\" é um monitor ultra-wide com resolução WQHD (3440x1440), taxa de atualização de 160Hz e suporte a G-Sync. Ideal para quem busca um monitor para jogos e produtividade.",
                "marca": "LG",
                "modelo": "34GN850-B",
                "imagem": "https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmonitor-gamer-lg-ultragear-lg-34-curvo.png?alt=media&token=7f00d9ba-f2ef-416e-bf01-0b84962e099b",
                "nota": 4.7,
                "videoReview": "https://www.youtube.com/embed/YUbQODIro2k",
                "tags": [
                    "Ultra-Wide",
                    "144Hz",
                    "G-Sync"
                ],
                "precoBase": 2999.99,
                "precoPromocional": 2399.99,
                "menorPreco": 2199.99,
                "maiorPreco": 3999.99,
                "precoMedio": 2899.99,
                "especificacoes": {
                    "peso": "7.3 kg",
                    "Tamanho": "34 polegadas",
                    "destaque": "Painel WQHD",
                    "Tecnologia": "IPS",
                    "Conectividade": "HDMI, DisplayPort, USB",
                    "Tempo de Resposta": "1ms",
                    "Taxa de Atualização": "160Hz"
                }
            },
            "quantidade": 1,
            "precoUnitario": 2399.99
        }
    ]
}